### ISSUE TITLE
.gitignore에 db 폴더 추가

### ISSUE THREAD

**Issue by hyuk0309** [prgrms-be-devcourse/BE-02-MarBox#18]
## 문제
- ./db 파일이 git에 의해 추적 된다. 그런./db 파일은 개발할 때마다 바뀌는 파일이다. 따라서 머지시 충돌 위험성이 있다. 

## 변경 전
- ./db 파일이 git에 의해 추적된다.

## 변경 후
- ./db 파일이 git에 의해 추적되지 않는다.

**Comment by sdardew** [comment]
merge 되었습니다. [링크](https://github.com/prgrms-be-devcourse/BE-02-MarBox/pull/22)
