### ISSUE TITLE
checkstyle과 java 호환 문제

### ISSUE THREAD

**Issue by hyuk0309** [prgrms-be-devcourse/BE-02-MarBox#23]
## 문제
- 현제 `build.gradle`에서 사용하는 checkstyle이 구버전이라 java 최신 문법을 분석하지 못함.

## 변경 전
- java 17 문법. ex)Record 를 checkstyle이 분석하지 못함.

## 변경 후
- checkstyle이 java 17 문법을 분석할 수 있음.

**Comment by sdardew** [comment]
[링크](https://github.com/prgrms-be-devcourse/BE-02-MarBox/pull/24)
