### ISSUE TITLE
Schedule 컨벤션 맞추기

### ISSUE THREAD

**Issue by yanJuicy** [prgrms-be-devcourse/BE-02-MarBox#32]
## 개요
- Schedule 클래스 관련 컨벤션 맞추기

## 설명
- ScheduleRecord -> RequestCreateSchedule 변경
- ScheduleConverter 클래스 추가

**Comment by sdardew** [comment]
[링크](https://github.com/prgrms-be-devcourse/BE-02-MarBox/pull/33)
