### ISSUE TITLE
예외 Dto 추가하기

### ISSUE THREAD

**Issue by hyuk0309** [prgrms-be-devcourse/BE-02-MarBox#34]
## 문제
- 응답에 대한 예외용 Dto가 없다.

## 변경 전
- 예외가 발생한 경우, 응답 API의 형태가 팀원마다 달랐다.

## 변경 후
- 예외가 발생하는 응답의 경우, 동일한 응답 API 형태로 응답한다.

**Comment by sdardew** [comment]
[링크](https://github.com/prgrms-be-devcourse/BE-02-MarBox/pull/36)
