### ISSUE TITLE
고객은 회원 가입할 수 있다. 

### ISSUE THREAD

**Issue by hyuk0309** [prgrms-be-devcourse/BE-02-MarBox#9]
## 개요
- 사용자 회원가입 기능 개발

## 설명
- 사용자는 email, password, name, role(CUSTOMER, ADMIN) 정보를 이용해 회원가입을 요청한다.
- 입력한 정보를 검증한다. (email, name의 유일성 검사)
- 입력한 정보를 DB에 저장한다.

**Comment by sdardew** [comment]
[링크](https://github.com/prgrms-be-devcourse/BE-02-MarBox/pull/29)
